/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'plan' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'debugClearInquiries' : IDL.Func([], [], []),
  'debugDeleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'debugGetAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisitCount' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'plan' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'debugClearInquiries' : IDL.Func([], [], []),
    'debugDeleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'debugGetAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisitCount' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };